/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bestdeal.gui;
import bestdeal.dao.ClientDAO;
import bestdeal.dao.DealDAO;
import bestdeal.dao.VendeurDAO;
import bestdeal.entities.Client;
import bestdeal.entities.Deal;
import bestdeal.entities.Vendeur;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ahmed
 */
public class AccueilAdmin extends javax.swing.JFrame {
    /**
     * Creates new form AccueilAdmin
     */
    static ImagePanel panel;
    public AccueilAdmin() {
        initComponents();
      
       jLabel2.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\Logo_.png"));
       cmd_EmailSend.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\email_iconp.png"));
       cmd_Reclamation.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\editpaste-256p.png"));
       cmd_AjouterCompteAdmin.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\add_adminp.png"));
       cmd_stat.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\statp.png"));
       cmd_listadmin.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\liste_adminp.png"));
       cmd_Logout.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\Logoutpp.png"));
       cmd_search.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\searchp.png"));
       cmd_setting.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\Setting-iconp.png"));
       lbl_im.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\bonjour.png"));
       panel = new ImagePanel(new ImageIcon("C:\\Users\\Jedidi\\Desktop\\11.jpg").getImage());
       jPanel1.add(panel);
       Cmd_Supprimer.setIcon((Icon) new ImageIcon("C:\\Users\\Jedidi\\Desktop\\icone\\supprimer.png"));
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combo_Menu = new javax.swing.JComboBox();
        txt_Rech = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Deals = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table_Vendeur = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Table_VendeurAttente = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Table_Client = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        Cmd_Supprimer = new javax.swing.JButton();
        cmd_Valide = new javax.swing.JButton();
        Cmd_ValiderClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmd_search = new javax.swing.JButton();
        Cmd_Vendeur = new javax.swing.JButton();
        cmd_EmailSend = new javax.swing.JButton();
        cmd_Reclamation = new javax.swing.JButton();
        cmd_AjouterCompteAdmin = new javax.swing.JButton();
        cmd_stat = new javax.swing.JButton();
        cmd_listadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmd_Logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_im = new javax.swing.JLabel();
        cmd_setting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 660));

        combo_Menu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Technologie", "Beaute", "Loisir", "Auto", " " }));

        jTabbedPane1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        Table_Deals.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Deals.setModel(new DealModel());
        jScrollPane1.setViewportView(Table_Deals);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Deals", jPanel2);

        jTable5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable5.setModel(new DealModel(5));
        jScrollPane4.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Deals en Attente", jPanel3);

        Table_Vendeur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Vendeur.setModel(new VendeurModel());
        jScrollPane9.setViewportView(Table_Vendeur);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vendeurs", jPanel4);

        Table_VendeurAttente.setModel(new VendeurModel(5));
        jScrollPane10.setViewportView(Table_VendeurAttente);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vendeurs en Attente", jPanel5);

        Table_Client.setModel(new ClientModel());
        jScrollPane11.setViewportView(Table_Client);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clients", jPanel6);

        jTable6.setModel(new ClientModel(5));
        jScrollPane12.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clients en Attente", jPanel7);

        Cmd_Supprimer.setMaximumSize(new java.awt.Dimension(160, 40));
        Cmd_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_SupprimerActionPerformed(evt);
            }
        });

        cmd_Valide.setText("Valide Deal");
        cmd_Valide.setMaximumSize(new java.awt.Dimension(160, 40));
        cmd_Valide.setPreferredSize(new java.awt.Dimension(90, 23));
        cmd_Valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ValideActionPerformed(evt);
            }
        });

        Cmd_ValiderClient.setText("Bloquer Client");
        Cmd_ValiderClient.setMaximumSize(new java.awt.Dimension(160, 40));
        Cmd_ValiderClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_ValiderClientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setText("Recherche ");

        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });

        Cmd_Vendeur.setText("Vendeur");
        Cmd_Vendeur.setMaximumSize(new java.awt.Dimension(160, 40));
        Cmd_Vendeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmd_VendeurActionPerformed(evt);
            }
        });

        cmd_EmailSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_EmailSendActionPerformed(evt);
            }
        });

        cmd_Reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ReclamationActionPerformed(evt);
            }
        });

        cmd_AjouterCompteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_AjouterCompteAdminActionPerformed(evt);
            }
        });

        cmd_stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_statActionPerformed(evt);
            }
        });

        cmd_listadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_listadminActionPerformed(evt);
            }
        });

        cmd_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_LogoutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jLabel3.setText("Bonjour, Med Amine");

        cmd_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_settingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(cmd_EmailSend, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_Reclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_AjouterCompteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_listadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Rech, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_im, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(combo_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(Cmd_Vendeur, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cmd_ValiderClient, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmd_Valide, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cmd_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmd_Reclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmd_AjouterCompteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmd_stat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmd_EmailSend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmd_listadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmd_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_im, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmd_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Rech, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(combo_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmd_Vendeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cmd_ValiderClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_Valide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cmd_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_ValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ValideActionPerformed
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex()==0){
     int ligneSelectionne = Table_Deals.getSelectedRow();
     DealDAO doo=new DealDAO();
     Deal d=new Deal();
     String idDeals = Table_Deals.getValueAt(ligneSelectionne, 0).toString();
     d.setId_deal(Integer.parseInt(idDeals));
     doo.updateDeal_ToValide(d);
     JOptionPane.showMessageDialog(null, " Deal valide ");
     Table_Deals.setModel(new DealModel());
     jTable5.setModel(new DealModel(5));

        }
        else if (jTabbedPane1.getSelectedIndex()==1)
        {
          int ligneSelectionne = jTable5.getSelectedRow();
     DealDAO doo=new DealDAO();
     Deal d=new Deal();
     String idDeals = jTable5.getValueAt(ligneSelectionne, 0).toString();
     d.setId_deal(Integer.parseInt(idDeals));
     doo.updateDeal_ToInvalide(d);
     JOptionPane.showMessageDialog(null, " Deal Non valide "); 
     Table_Deals.setModel(new DealModel());
     jTable5.setModel(new DealModel(5));

        }
      // System.out.println("Table deals clicked : "+nom_deal+"  "+description+" "+id_vendeur);
              
          
        
        
    }//GEN-LAST:event_cmd_ValideActionPerformed

    
    
    private void Cmd_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_SupprimerActionPerformed
        // TODO add your handling code here:
 
            
        if (jTabbedPane1.getSelectedIndex()==4){
            
      JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
      int ligneSelectionne = Table_Client.getSelectedRow();
      Table_Client.getValueAt(ligneSelectionne, 0);
      
   String idClient = Table_Client.getValueAt(ligneSelectionne, 0).toString();
     String login = Table_Client.getValueAt(ligneSelectionne, 1).toString();
       String pwd = Table_Client.getValueAt(ligneSelectionne, 2).toString();
        String nom = Table_Client.getValueAt(ligneSelectionne, 3).toString();
         String prenom= Table_Client.getValueAt(ligneSelectionne, 4).toString();
          String email = Table_Client.getValueAt(ligneSelectionne, 5).toString();
          String etat = Table_Client.getValueAt(ligneSelectionne, 6).toString();
            System.out.println("Colone clicked "+login+pwd+nom+prenom+email+etat+idClient);
            
            Client c=new Client();
           
            c.setId_client(Integer.parseInt(idClient));
            c.setLogin(login);
            c.setPwd(pwd);
            c.setPrenom(prenom);
            c.setNom(nom);
            c.setEmail(email);
            
            ClientDAO cd=new ClientDAO();
            cd.deleteClient(c);}else {}
           Table_Client.setModel(new ClientModel());
        }      
        else if (jTabbedPane1.getSelectedIndex()==0)
        {
             JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
             int ligneSelectionne = Table_Deals.getSelectedRow();
             Table_Deals.getValueAt(ligneSelectionne, 0);
      
       String idDeals = Table_Deals.getValueAt(ligneSelectionne, 0).toString();
       Deal d1=new Deal();
       d1.setId_deal(Integer.parseInt(idDeals));
       DealDAO do1=new DealDAO();
       do1.deleteClient(d1);
       System.out.println("Table deals clicked : "+idDeals);
       Table_Deals.setModel(new DealModel());
     }
     else {}
        }
        else if (jTabbedPane1.getSelectedIndex()==5)
        {
             JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
            int ligneSelectionne = jTable6.getSelectedRow();
      jTable6.getValueAt(ligneSelectionne, 0);  
      String idClient = jTable6.getValueAt(ligneSelectionne, 0).toString();
       Client c=new Client();
           
            c.setId_client(Integer.parseInt(idClient));
           
            ClientDAO cd=new ClientDAO();
           cd.deleteClient(c);
          System.out.println("Table client en Attente Client : "+idClient); 
          jTable6.setModel(new ClientModel(5));
     }
     else {}
      
        }  else if (jTabbedPane1.getSelectedIndex()==1)
        {
             JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
             int ligneSelectionne = jTable5.getSelectedRow();
             jTable5.getValueAt(ligneSelectionne, 0);
      
       String idDeals = jTable5.getValueAt(ligneSelectionne, 0).toString();
       Deal d1=new Deal();
       d1.setId_deal(Integer.parseInt(idDeals));
       DealDAO do1=new DealDAO();
       do1.deleteClient(d1);
       
       System.out.println("Table deals en Attente clicked : "+idDeals);
       jTable5.setModel(new DealModel(5));
     }
     else {}
        }
        else if (jTabbedPane1.getSelectedIndex()==2)
        {
             JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
             int ligneSelectionne = Table_Vendeur.getSelectedRow();
             Table_Vendeur.getValueAt(ligneSelectionne, 0);
              String idVendeur = Table_Vendeur.getValueAt(ligneSelectionne, 0).toString();
              Vendeur v=new Vendeur();
               v.setId_vendeur(Integer.parseInt(idVendeur));
               VendeurDAO vv=new VendeurDAO();
               vv.deleteVendeur(v);
               Table_Vendeur.setModel(new VendeurModel());
     }
     else {}
        }   else if (jTabbedPane1.getSelectedIndex()==3)
        {
             JOptionPane confirmation = new JOptionPane();
     int i=JOptionPane.showConfirmDialog(null, "La suppression est irréversible. Êtes-vous sûr de vouloir continuer?",
                                    "Veuillez confirmer votre choix",
                                    JOptionPane.YES_NO_OPTION);
     if(i==0){
             int ligneSelectionne = Table_VendeurAttente.getSelectedRow();
             Table_VendeurAttente.getValueAt(ligneSelectionne, 0);
              String idVendeur = Table_VendeurAttente.getValueAt(ligneSelectionne, 0).toString();
              Vendeur v=new Vendeur();
               v.setId_vendeur(Integer.parseInt(idVendeur));
               VendeurDAO vv=new VendeurDAO();
               vv.deleteVendeur(v);
               Table_VendeurAttente.setModel(new VendeurModel(5));
     }
     else {}
        }
        
        
    }//GEN-LAST:event_Cmd_SupprimerActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
 //here 
      if (jTabbedPane1.getSelectedIndex()==0)
         {
             cmd_Valide.setText("Bloquer Deal ");
        }
        else if (jTabbedPane1.getSelectedIndex()==1)
        {
            cmd_Valide.setText(" Débloquer Deal ");
        }
       else if (jTabbedPane1.getSelectedIndex()==2)
        {
            Cmd_Vendeur.setText(" Bloquer Vendeur ");
        }
       else if (jTabbedPane1.getSelectedIndex()==3)
        {
            Cmd_Vendeur.setText(" Débloquer Vendeur ");
        }
       else if (jTabbedPane1.getSelectedIndex()==4)
        {
            Cmd_ValiderClient.setText(" Bloquer Client ");
        }
       else if (jTabbedPane1.getSelectedIndex()==5)
        {
            Cmd_ValiderClient.setText(" Débloquer Client ");
        }
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
      
               
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void Cmd_ValiderClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_ValiderClientActionPerformed
        // TODO add your handling code here:
       
    if(jTabbedPane1.getSelectedIndex()==4){
      int ligneSelectionne = Table_Client.getSelectedRow();
      ClientDAO cd=new ClientDAO();
      Client c=new Client();
     
      String idClient = Table_Client.getValueAt(ligneSelectionne, 0).toString();
      c.setId_client(Integer.parseInt(idClient));
      cd.updateClient_ToInvalide(c);
   
     JOptionPane.showMessageDialog(null, " Client Bloquer avec succès ");
     jTable6.setModel(new ClientModel(5));
     Table_Client.setModel(new ClientModel());  
        }
            else if(jTabbedPane1.getSelectedIndex()==5){
                
     int ligneSelectionne = jTable6.getSelectedRow();
        
     ClientDAO cd=new ClientDAO();
     Client c=new Client();
     
     String idClient = jTable6.getValueAt(ligneSelectionne, 0).toString();
     c.setId_client(Integer.parseInt(idClient));
     cd.updateClient_ToValide(c);
   
     JOptionPane.showMessageDialog(null, " Client Debloquer avec succès ");
     jTable6.setModel(new ClientModel(5));
     Table_Client.setModel(new ClientModel());

               
            }
        
    }//GEN-LAST:event_Cmd_ValiderClientActionPerformed

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed
        // TODO add your handling code here:
        //Methode de recherche exp
        if(txt_Rech.getText().equals("")!=false){
            
      JOptionPane.showMessageDialog(null, " Veuillez entrer une chaîne pour la recherche  ");

        if (jTabbedPane1.getSelectedIndex()==4){
       String b=  txt_Rech.getText();
       Table_Client.setModel(new ClientModel(8, b));
        }
        else if (jTabbedPane1.getSelectedIndex()==5)
        {
            String b=txt_Rech.getText();
            jTable6.setModel(new ClientModel(5, b));
        }
        else if (jTabbedPane1.getSelectedIndex()==2)
        {
            String b=txt_Rech.getText();
            Table_Vendeur.setModel(new VendeurModel(5, b));
        }
        else if (jTabbedPane1.getSelectedIndex()==3)
        {
             String b=txt_Rech.getText();
            Table_VendeurAttente.setModel(new VendeurModel(5, b));
           
        }else if (jTabbedPane1.getSelectedIndex()==0)
        {
            String b=txt_Rech.getText();
            Table_Deals.setModel(new DealModel(5, b));
        }
        else if (jTabbedPane1.getSelectedIndex()==1)
        {
            String b=txt_Rech.getText();
            jTable5.setModel(new DealModel(5, b));
        }
        }else {System.out.println();}
        
    }//GEN-LAST:event_cmd_searchActionPerformed

    private void Cmd_VendeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmd_VendeurActionPerformed
        // TODO add your handling code here:
        
           if(jTabbedPane1.getSelectedIndex()==2){
      int ligneSelectionne = Table_Vendeur.getSelectedRow();
     
      VendeurDAO vv=new VendeurDAO();
      Vendeur v=new Vendeur();
    
      String idVendeur = Table_Vendeur.getValueAt(ligneSelectionne, 0).toString();
      v.setId_vendeur(Integer.parseInt(idVendeur));
      vv.updateVendeur_ToInvalide(v);
     JOptionPane.showMessageDialog(null, " Vendeur Bloquer avec succès ");
     Table_Vendeur.setModel(new VendeurModel());
     Table_VendeurAttente.setModel(new VendeurModel(5));

  
        }
            else if(jTabbedPane1.getSelectedIndex()==3){
                
      int ligneSelectionne = Table_VendeurAttente.getSelectedRow();
     
      VendeurDAO vv=new VendeurDAO();
      Vendeur v=new Vendeur();
    
      String idVendeur = Table_VendeurAttente.getValueAt(ligneSelectionne, 0).toString();
      v.setId_vendeur(Integer.parseInt(idVendeur));
      vv.updateVendeur_Tovalide(v);
     JOptionPane.showMessageDialog(null, " Vendeur Débloquer avec succès ");
           Table_VendeurAttente.setModel(new VendeurModel(5));
           Table_Vendeur.setModel(new VendeurModel());

            }
           
    }//GEN-LAST:event_Cmd_VendeurActionPerformed

    private void cmd_EmailSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_EmailSendActionPerformed
        // TODO add your handling code here:
        
        MailAdmin ma=new MailAdmin();
        ma.show();
        
        
        
    }//GEN-LAST:event_cmd_EmailSendActionPerformed

    private void cmd_AjouterCompteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_AjouterCompteAdminActionPerformed
        // TODO add your handling code here:
        AjouterAdmin aj=new AjouterAdmin();
        aj.show();
    }//GEN-LAST:event_cmd_AjouterCompteAdminActionPerformed

    private void cmd_statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_statActionPerformed
        // TODO add your handling code here:
        
        Statistique st=new Statistique();
        st.show();
        
    }//GEN-LAST:event_cmd_statActionPerformed

    private void cmd_ReclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ReclamationActionPerformed
        
        ListeReclamation rc=new ListeReclamation();
        rc.show();
    }//GEN-LAST:event_cmd_ReclamationActionPerformed

    private void cmd_listadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_listadminActionPerformed
        // TODO add your handling code here:
        
        ListeAdmin ls=new ListeAdmin();
        ls.show();
        
    }//GEN-LAST:event_cmd_listadminActionPerformed

    private void cmd_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_LogoutActionPerformed

    private void cmd_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_settingActionPerformed
        CompteAdmin ca = new CompteAdmin();
        ca.show();
    }//GEN-LAST:event_cmd_settingActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cmd_Supprimer;
    private javax.swing.JButton Cmd_ValiderClient;
    private javax.swing.JButton Cmd_Vendeur;
    private javax.swing.JTable Table_Client;
    private javax.swing.JTable Table_Deals;
    private javax.swing.JTable Table_Vendeur;
    private javax.swing.JTable Table_VendeurAttente;
    private javax.swing.JButton cmd_AjouterCompteAdmin;
    private javax.swing.JButton cmd_EmailSend;
    private javax.swing.JButton cmd_Logout;
    private javax.swing.JButton cmd_Reclamation;
    private javax.swing.JButton cmd_Valide;
    private javax.swing.JButton cmd_listadmin;
    private javax.swing.JButton cmd_search;
    private javax.swing.JButton cmd_setting;
    private javax.swing.JButton cmd_stat;
    private javax.swing.JComboBox combo_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel lbl_im;
    private javax.swing.JTextField txt_Rech;
    // End of variables declaration//GEN-END:variables
}
class ImagePanel extends JPanel {
  /**
 * 
 */
private static final long serialVersionUID = 1L;
private Image img;

  public ImagePanel(String img) {
    this(new ImageIcon(img).getImage());
  }

  public ImagePanel(Image img) {
    this.img = img;
    Dimension size = new Dimension(img.getWidth(null), img.getHeight(null));
    setPreferredSize(size);
    setMinimumSize(size);
    setMaximumSize(size);
    setSize(size);
    setLayout(null);
  }

  public void paintComponent(Graphics g) {
    g.drawImage(img, 0, 0, null);
  }

}